language: ruby
rvm:
- 2.5
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.6"
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database products_test;' -U postgres
script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
