
---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: products_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: |
            gem update --system
            gem install bundler
            bundle check || bundle install --jobs=3 --retry=3

      - run:
          name: DB setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate RAILS_ENV=test

      - run:
          name: Wait for DB
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run the tests
          command: |
            bundle exec rspec

