kind: pipeline
name: default

steps:
- name: build
  image: ruby:2.5.3
  commands:
  - gem update --system
  - gem install bundler
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database products_test;' -U postgres -h database
  - bundle install --jobs=3 --retry=3
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
  when:
    event:
    - push
    - pull-request
    branch:
    - master
    - feature/*

services:
- name: database
  image: postgres:9.6
