name: Docker Image CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
      - 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unboxit/rorapi:$(date +%s)
