name: Ruby

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Cache
      uses: actions/cache@v1.0.0
    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0
    - name: Pronto Ruby
      uses: AdWerx/pronto-ruby@v1.0.0-rc3
    - name: Build and test with RSpec
      run: |
        gem update --system
        gem install bundler
        bundle install --jobs=3 --retry=3
        bundle exec rails db:create
        bundle exec rails db:migrate RAILS_ENV=test
        bundle exec rspec
