name: Ruby
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services: 
      db: 
        image: postgres
        ports:
          - "5432:5432"
        options: |
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:@localhost:5432/products_test
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs=3 --retry=3
        bundle exec rails db:setup
        bundle exec rails db:migrate RAILS_ENV=test
        bundle exec rspec
